-- 中文作文工作室：補足 5CW1–5CW4 至80題，建立作文輸入、儲存、自動評改及老師評語資料表。
begin;

create table if not exists public.writing_prompts(
  id bigint generated by default as identity primary key,
  node_id bigint not null references public.curriculum_nodes(id) on delete cascade,
  genre text not null, title text not null, instruction text not null,
  min_chars integer not null default 350, max_chars integer not null default 650,
  guidance jsonb not null default '[]'::jsonb, status text not null default 'published',
  sort_order integer not null default 0, created_at timestamptz not null default now(),
  unique(node_id,title)
);
create table if not exists public.writing_submissions(
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  prompt_id bigint not null references public.writing_prompts(id) on delete cascade,
  content text not null, char_count integer not null,
  automated_score integer not null, rubric_breakdown jsonb not null default '{}'::jsonb,
  automated_feedback text not null, teacher_score integer,
  teacher_feedback text, status text not null default 'submitted',
  submitted_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists writing_submissions_student_idx on public.writing_submissions(student_id,submitted_at desc);
alter table public.writing_prompts enable row level security;
alter table public.writing_submissions enable row level security;
drop policy if exists writing_prompts_read on public.writing_prompts;
create policy writing_prompts_read on public.writing_prompts for select to authenticated using(status='published');
drop policy if exists writing_submissions_own_read on public.writing_submissions;
create policy writing_submissions_own_read on public.writing_submissions for select to authenticated using(student_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists writing_submissions_own_insert on public.writing_submissions;
create policy writing_submissions_own_insert on public.writing_submissions for insert to authenticated with check(student_id=auth.uid());
drop policy if exists writing_submissions_admin_update on public.writing_submissions;
create policy writing_submissions_admin_update on public.writing_submissions for update to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create temporary table tmp_prompts(node_code text,genre text,title text,instruction text,min_chars int,max_chars int,guidance jsonb,sort_order int) on commit drop;
insert into tmp_prompts values
  ('5CW1','記敘文','一次意外的幫助','以「一次意外的幫助」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,1),
  ('5CW1','記敘文','我終於做到了','以「我終於做到了」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,2),
  ('5CW1','記敘文','難忘的校外學習','以「難忘的校外學習」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,3),
  ('5CW1','記敘文','一個誠實的選擇','以「一個誠實的選擇」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,4),
  ('5CW1','記敘文','風雨中的合作','以「風雨中的合作」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,5),
  ('5CW1','記敘文','我和新同學','以「我和新同學」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,6),
  ('5CW1','記敘文','第一次獨自完成任務','以「第一次獨自完成任務」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,7),
  ('5CW1','記敘文','一句鼓勵的話','以「一句鼓勵的話」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,8),
  ('5CW1','記敘文','失敗後的改變','以「失敗後的改變」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,9),
  ('5CW1','記敘文','最溫暖的一天','以「最溫暖的一天」為題，寫一篇記敘文。交代事情的起因、經過和結果，並寫出人物感受。',350,650,'["起因","經過","結果","感受"]'::jsonb,10),
  ('5CW2','描寫文','清晨的公園','以「清晨的公園」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,1),
  ('5CW2','描寫文','雨中的街道','以「雨中的街道」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,2),
  ('5CW2','描寫文','熱鬧的年宵市場','以「熱鬧的年宵市場」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,3),
  ('5CW2','描寫文','寧靜的圖書館','以「寧靜的圖書館」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,4),
  ('5CW2','描寫文','黃昏的海邊','以「黃昏的海邊」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,5),
  ('5CW2','描寫文','比賽前的運動場','以「比賽前的運動場」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,6),
  ('5CW2','描寫文','祖母的廚房','以「祖母的廚房」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,7),
  ('5CW2','描寫文','春天的校園','以「春天的校園」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,8),
  ('5CW2','描寫文','繁忙的車站','以「繁忙的車站」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,9),
  ('5CW2','描寫文','我最喜愛的房間','以「我最喜愛的房間」為題，寫一篇描寫文。運用視覺、聽覺或觸覺細節，寫出景物及氣氛。',350,650,'["觀察","感官","次序","氣氛"]'::jsonb,10),
  ('5CW3','說明文','節約食水的方法','以「節約食水的方法」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,1),
  ('5CW3','說明文','健康早餐的重要','以「健康早餐的重要」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,2),
  ('5CW3','說明文','如何安全上網','以「如何安全上網」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,3),
  ('5CW3','說明文','建立閱讀習慣','以「建立閱讀習慣」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,4),
  ('5CW3','說明文','垃圾分類的步驟','以「垃圾分類的步驟」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,5),
  ('5CW3','說明文','照顧植物的方法','以「照顧植物的方法」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,6),
  ('5CW3','說明文','乘搭公共交通的好處','以「乘搭公共交通的好處」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,7),
  ('5CW3','說明文','颱風前的準備','以「颱風前的準備」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,8),
  ('5CW3','說明文','保護海洋的方法','以「保護海洋的方法」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,9),
  ('5CW3','說明文','良好時間管理','以「良好時間管理」為題，寫一篇說明文。先說明目的，再有條理地解釋原因、方法或步驟。',350,650,'["目的","分點","例子","總結"]'::jsonb,10),
  ('5CW4','實用文','班會通知','完成一篇「班會通知」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,1),
  ('5CW4','實用文','活動邀請信','完成一篇「活動邀請信」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,2),
  ('5CW4','實用文','遺失物品啟事','完成一篇「遺失物品啟事」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,3),
  ('5CW4','實用文','感謝義工的信','完成一篇「感謝義工的信」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,4),
  ('5CW4','實用文','活動取消通告','完成一篇「活動取消通告」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,5),
  ('5CW4','實用文','圖書館規則','完成一篇「圖書館規則」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,6),
  ('5CW4','實用文','郊遊備忘','完成一篇「郊遊備忘」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,7),
  ('5CW4','實用文','比賽報名通知','完成一篇「比賽報名通知」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,8),
  ('5CW4','實用文','給同學的建議信','完成一篇「給同學的建議信」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,9),
  ('5CW4','實用文','社區活動宣傳單張','完成一篇「社區活動宣傳單張」。使用合適格式，清楚交代對象、目的、日期、地點或聯絡資料。',350,650,'["對象","目的","資料","格式"]'::jsonb,10);
insert into public.writing_prompts(node_id,genre,title,instruction,min_chars,max_chars,guidance,sort_order,status)
select n.id,t.genre,t.title,t.instruction,t.min_chars,t.max_chars,t.guidance,t.sort_order,'published'
from tmp_prompts t join public.curriculum_nodes n on n.code=t.node_code
on conflict(node_id,title) do update set instruction=excluded.instruction,min_chars=excluded.min_chars,max_chars=excluded.max_chars,guidance=excluded.guidance,sort_order=excluded.sort_order,status='published';

create temporary table tmp_extra_questions(node_code text,question_text text,options jsonb,correct_answer jsonb,explanation text,difficulty int) on commit drop;
insert into tmp_extra_questions values
  ('5CW1','【新增寫作技巧】以「一次改變計劃的經歷」寫記敘文時，哪一項最重要？','[{"id":"a","text":"事件完整並寫出感受"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'記敘文應做到：事件完整並寫出感受。',3),
  ('5CW1','【新增寫作技巧】完成「一次改變計劃的經歷」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW1','【新增寫作技巧】以「校園裏的新發現」寫記敘文時，哪一項最重要？','[{"id":"a","text":"事件完整並寫出感受"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'記敘文應做到：事件完整並寫出感受。',3),
  ('5CW1','【新增寫作技巧】完成「校園裏的新發現」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW1','【新增寫作技巧】以「窗外的雨景」寫記敘文時，哪一項最重要？','[{"id":"a","text":"事件完整並寫出感受"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'記敘文應做到：事件完整並寫出感受。',3),
  ('5CW1','【新增寫作技巧】完成「窗外的雨景」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW1','【新增寫作技巧】以「節日裏的街道」寫記敘文時，哪一項最重要？','[{"id":"a","text":"事件完整並寫出感受"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'記敘文應做到：事件完整並寫出感受。',3),
  ('5CW1','【新增寫作技巧】完成「節日裏的街道」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW1','【新增寫作技巧】以「如何保持課室整潔」寫記敘文時，哪一項最重要？','[{"id":"a","text":"事件完整並寫出感受"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'記敘文應做到：事件完整並寫出感受。',3),
  ('5CW1','【新增寫作技巧】完成「如何保持課室整潔」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW2','【新增寫作技巧】以「一次改變計劃的經歷」寫描寫文時，哪一項最重要？','[{"id":"a","text":"運用具體感官和景物細節"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'描寫文應做到：運用具體感官和景物細節。',3),
  ('5CW2','【新增寫作技巧】完成「一次改變計劃的經歷」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW2','【新增寫作技巧】以「校園裏的新發現」寫描寫文時，哪一項最重要？','[{"id":"a","text":"運用具體感官和景物細節"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'描寫文應做到：運用具體感官和景物細節。',3),
  ('5CW2','【新增寫作技巧】完成「校園裏的新發現」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW2','【新增寫作技巧】以「窗外的雨景」寫描寫文時，哪一項最重要？','[{"id":"a","text":"運用具體感官和景物細節"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'描寫文應做到：運用具體感官和景物細節。',3),
  ('5CW2','【新增寫作技巧】完成「窗外的雨景」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW2','【新增寫作技巧】以「節日裏的街道」寫描寫文時，哪一項最重要？','[{"id":"a","text":"運用具體感官和景物細節"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'描寫文應做到：運用具體感官和景物細節。',3),
  ('5CW2','【新增寫作技巧】完成「節日裏的街道」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW2','【新增寫作技巧】以「如何保持課室整潔」寫描寫文時，哪一項最重要？','[{"id":"a","text":"運用具體感官和景物細節"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'描寫文應做到：運用具體感官和景物細節。',3),
  ('5CW2','【新增寫作技巧】完成「如何保持課室整潔」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW3','【新增寫作技巧】以「一次改變計劃的經歷」寫說明文時，哪一項最重要？','[{"id":"a","text":"按清楚層次解釋資料"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'說明文應做到：按清楚層次解釋資料。',3),
  ('5CW3','【新增寫作技巧】完成「一次改變計劃的經歷」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW3','【新增寫作技巧】以「校園裏的新發現」寫說明文時，哪一項最重要？','[{"id":"a","text":"按清楚層次解釋資料"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'說明文應做到：按清楚層次解釋資料。',3),
  ('5CW3','【新增寫作技巧】完成「校園裏的新發現」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW3','【新增寫作技巧】以「窗外的雨景」寫說明文時，哪一項最重要？','[{"id":"a","text":"按清楚層次解釋資料"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'說明文應做到：按清楚層次解釋資料。',3),
  ('5CW3','【新增寫作技巧】完成「窗外的雨景」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW3','【新增寫作技巧】以「節日裏的街道」寫說明文時，哪一項最重要？','[{"id":"a","text":"按清楚層次解釋資料"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'說明文應做到：按清楚層次解釋資料。',3),
  ('5CW3','【新增寫作技巧】完成「節日裏的街道」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW3','【新增寫作技巧】以「如何保持課室整潔」寫說明文時，哪一項最重要？','[{"id":"a","text":"按清楚層次解釋資料"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'說明文應做到：按清楚層次解釋資料。',3),
  ('5CW3','【新增寫作技巧】完成「如何保持課室整潔」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW4','【新增寫作技巧】以「一次改變計劃的經歷」寫實用文時，哪一項最重要？','[{"id":"a","text":"格式、對象和重要資料齊全"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'實用文應做到：格式、對象和重要資料齊全。',3),
  ('5CW4','【新增寫作技巧】完成「一次改變計劃的經歷」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW4','【新增寫作技巧】以「校園裏的新發現」寫實用文時，哪一項最重要？','[{"id":"a","text":"格式、對象和重要資料齊全"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'實用文應做到：格式、對象和重要資料齊全。',3),
  ('5CW4','【新增寫作技巧】完成「校園裏的新發現」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW4','【新增寫作技巧】以「窗外的雨景」寫實用文時，哪一項最重要？','[{"id":"a","text":"格式、對象和重要資料齊全"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'實用文應做到：格式、對象和重要資料齊全。',3),
  ('5CW4','【新增寫作技巧】完成「窗外的雨景」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW4','【新增寫作技巧】以「節日裏的街道」寫實用文時，哪一項最重要？','[{"id":"a","text":"格式、對象和重要資料齊全"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'實用文應做到：格式、對象和重要資料齊全。',3),
  ('5CW4','【新增寫作技巧】完成「節日裏的街道」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3),
  ('5CW4','【新增寫作技巧】以「如何保持課室整潔」寫實用文時，哪一項最重要？','[{"id":"a","text":"格式、對象和重要資料齊全"},{"id":"b","text":"加入大量無關內容"},{"id":"c","text":"故意刪去重要資料"},{"id":"d","text":"不分段並重複題目"}]'::jsonb,'"a"'::jsonb,'實用文應做到：格式、對象和重要資料齊全。',3),
  ('5CW4','【新增寫作技巧】完成「如何保持課室整潔」初稿後，最合適的修改方法是甚麼？','[{"id":"a","text":"檢查內容是否切題、段落是否清楚及標點是否正確"},{"id":"b","text":"只更換文章標題"},{"id":"c","text":"刪去所有細節"},{"id":"d","text":"不閱讀便立即提交"}]'::jsonb,'"a"'::jsonb,'修改時要從內容、結構、字詞和標點多方面檢查。',3);
insert into public.questions(node_id,question_type,question_text,options,difficulty,source_type,status)
select n.id,'multiple_choice',t.question_text,t.options,t.difficulty,'teacher','published'
from tmp_extra_questions t join public.curriculum_nodes n on n.code=t.node_code
where not exists(select 1 from public.questions q where q.node_id=n.id and q.question_text=t.question_text);
insert into public.question_answer_keys(question_id,correct_answer,explanation,hint)
select q.id,t.correct_answer,t.explanation,'完成初稿後，檢查切題、結構、字詞和標點。'
from tmp_extra_questions t join public.curriculum_nodes n on n.code=t.node_code join public.questions q on q.node_id=n.id and q.question_text=t.question_text
on conflict(question_id) do update set correct_answer=excluded.correct_answer,explanation=excluded.explanation,hint=excluded.hint;

create or replace function public.start_writing_task(p_node_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.writing_prompts;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into p from public.writing_prompts where node_id=p_node_id and status='published' order by random() limit 1;
  if p.id is null then return jsonb_build_object('success',false,'reason','no_prompt'); end if;
  return jsonb_build_object('success',true,'prompt_id',p.id,'genre',p.genre,'title',p.title,'instruction',p.instruction,'min_chars',p.min_chars,'max_chars',p.max_chars,'guidance',p.guidance);
end $$;

create or replace function public.submit_writing_task(p_prompt_id bigint,p_content text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.writing_prompts; chars int; paras int; punct int; length_score int; paragraph_score int; punctuation_score int; content_score int; total int; keyword_hits int; result_id bigint; feedback text;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into p from public.writing_prompts where id=p_prompt_id and status='published';
  if p.id is null then return jsonb_build_object('success',false,'reason','prompt_not_found'); end if;
  chars:=char_length(regexp_replace(coalesce(p_content,''),'[[:space:]]','','g'));
  if chars<50 then return jsonb_build_object('success',false,'reason','too_short'); end if;
  paras:=greatest(1,array_length(regexp_split_to_array(trim(p_content),E'\n[[:space:]]*\n'),1));
  punct:=char_length(p_content)-char_length(regexp_replace(p_content,'[，。！？；：、]','','g'));
  length_score:=case when chars between p.min_chars and p.max_chars then 30 when chars>=p.min_chars*0.75 then 22 when chars>=p.min_chars*0.5 then 15 else 8 end;
  paragraph_score:=case when paras>=4 then 20 when paras=3 then 17 when paras=2 then 11 else 5 end;
  punctuation_score:=case when punct>=14 then 20 when punct>=9 then 15 when punct>=5 then 10 else 5 end;
  select count(*) into keyword_hits from jsonb_array_elements_text(p.guidance) k where position(k in p_content)>0;
  content_score:=least(30,10+keyword_hits*5);
  total:=length_score+paragraph_score+punctuation_score+content_score;
  feedback:=case when length_score<22 then '篇幅稍短，可補充具體經過或例子。 ' else '篇幅完整。 ' end || case when paragraph_score<17 then '建議按內容分成至少三段。 ' else '段落安排清楚。 ' end || case when punctuation_score<15 then '請檢查句號、逗號和其他標點。 ' else '標點運用大致充足。 ' end || case when content_score<25 then '可加入更多題目要求的重點。' else '內容能回應主要寫作要求。' end;
  insert into public.writing_submissions(student_id,prompt_id,content,char_count,automated_score,rubric_breakdown,automated_feedback)
  values(auth.uid(),p.id,p_content,chars,total,jsonb_build_object('篇幅',length_score,'段落',paragraph_score,'標點',punctuation_score,'內容重點',content_score),feedback) returning id into result_id;
  return jsonb_build_object('success',true,'submission_id',result_id,'score',total,'char_count',chars,'rubric',jsonb_build_object('篇幅',length_score,'段落',paragraph_score,'標點',punctuation_score,'內容重點',content_score),'feedback',feedback);
end $$;
grant execute on function public.start_writing_task(bigint) to authenticated;
grant execute on function public.submit_writing_task(bigint,text) to authenticated;
commit;

select n.code,n.title_zh,count(q.id) filter(where q.status='published') as skill_questions,count(distinct wp.id) as writing_prompts
from public.curriculum_nodes n left join public.questions q on q.node_id=n.id left join public.writing_prompts wp on wp.node_id=n.id
where n.code in('5CW1','5CW2','5CW3','5CW4') group by n.code,n.title_zh order by n.code;
